id: P83684386
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22379
  title: གཞུང་ཆེན་བཀའ་པོད་ལྔའི་རྩ་བ།
  volumes:
    ed21fa3631e94ec191adcd96607e7229:
      image_group_id: I1KG22400
      title: ''
      base_file: v001.txt
  author: ''
